services:
  rah:
    image: pluswerk/php-dev:nginx-8.3-alpine
    init: true
    ipc: host
    privileged: true
    user: 1000:1000
    working_dir: ${PWD}
    volumes:
      - ./storage-root:/storage
      - .:${PWD}
      - ~/.ssh:/home/application/.ssh
      - ~/.gitconfig:/home/application/.gitconfig
      # container config:
      - ./bin/startup-ensure-api-key-created.sh:/opt/docker/provision/entrypoint.d/99-startup-ensure-api-key-created.sh
#      - ./nginx-config/vhost.conf:/opt/docker/etc/nginx/vhost.conf
      # open phpstorm from inside the container on Windows:
      - /mnt/:/mnt/
      - /run/WSL:/run/WSL
      - /init:/init:ro
      - /usr/bin/wslpath:/usr/bin/wslpath:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      VIRTUAL_HOST: rah.${TLD_DOMAIN:?TLD_DOMAIN is required},*.rah.${TLD_DOMAIN:?TLD_DOMAIN is required},test.rah.${TLD_DOMAIN:?TLD_DOMAIN is required}
      RAH_HOSTNAME: rah.${TLD_DOMAIN:?TLD_DOMAIN is required}

      WEB_DOCUMENT_ROOT: $PWD/public
      RAH_STORAGE_PATH: ${RAH_STORAGE_PATH:-/storage}
      RAH_MAX_DISK_USAGE: ${RAH_MAX_DISK_USAGE:-10G}
      # allows access to all deployments if client has ip from list
      RAH_AUTH_IPS: "213.61.68.122,private_ranges"
      # allows access to all deployments if client uses this auth
      RAH_BASIC_AUTH: "rah:passRah,customer:passCustomer"

       # open phpstorm from inside the container on Windows:
      PATH: $PATH
      WSL2_GUI_APPS_ENABLED: $WSL2_GUI_APPS_ENABLED
      WSL_INTEROP: $WSL_INTEROP
      PULSE_SERVER: $PULSE_SERVER
      WSLENV: $WSLENV
      WSL_DISTRO_NAME: $WSL_DISTRO_NAME
      LAUNCH_EDITOR: ${LAUNCH_EDITOR:-code-insiders}

networks:
  default:
    name: global
    external: true
