services:
  rah:
    image: andersundsehr/rah:latest
    init: true
    volumes:
      - storage:/storage
    environment:
      RAH_HOSTNAME: ${RAH_HOSTNAME:-rah.localhost}
      RAH_MAX_DISK_USAGE: '10G'
      # allows access to all deployments if client has ip from list
      RAH_AUTH_IPS: "213.61.68.122,private_ranges"
      # allows access to all deployments if client uses this auth
      RAH_BASIC_AUTH: "rah:rah"
    ports:
      - "3333:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
volumes:
  storage:
