services:
  rah:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    volumes:
      - ./storage:/storage
      - .:/app
      - ~/.ssh:/home/application/.ssh
      - ~/.gitconfig:/home/application/.gitconfig
#      - ./nginx-config/vhost.conf:/opt/docker/etc/nginx/vhost.conf
    environment:
      RAH_HOSTNAME: ${RAH_HOSTNAME:-rah.localhost}
      RAH_PORT: ${RAH_PORT:-80}
      # allows access to all deployments if client has ip from list
      RAH_AUTH_IPS: "213.61.68.122,127.0.0.1"
      # allows access to all deployments if client uses this auth
      RAH_BASIC_AUTH: "rah:rah"
    ports:
      - "3333:80"
    develop:
      watch:
#        - action: sync
#          path: .
#          target: /app
        - action: rebuild
          path: Dockerfile


#volumes:
#  storage:
